services:
  deepshield:
    image: neevan0842/deepshield-dfd:latest
    container_name: deepshield
    runtime: nvidia # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      # - "5000:5000" # Map port 5000 for the Flask API
      - "8501:8501" # Map port 8501 for Streamlit
    # command: ["python3", "app/main.py"] # Start the Flask API
    command: ["streamlit", "run", "app/ui.py"] # Start the Streamlit app
    develop:
      watch:
        - action: sync
          path: .
          target: /workspace
