name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Run this workflow only when pushing to 'main' branch
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Enable QEMU for multi-platform builds (e.g., ARM64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Enable Docker Buildx (faster & supports multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and Push Docker Image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64 # Supports both x86_64 and ARM
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/deepshield-dfd:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/deepshield-dfd:latest
